"""add is_guide to courses

Revision ID: 087dcada83c6
Revises: df108845fe91
Create Date: 2026-03-31 01:58:05.655107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087dcada83c6'
down_revision: Union[str, Sequence[str], None] = 'df108845fe91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('section_courses_section_id_course_id_key'), 'section_courses', type_='unique')
    op.create_unique_constraint(None, 'section_courses', ['section_id', 'course_id', 'section_part'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section_courses', type_='unique')
    op.create_unique_constraint(op.f('section_courses_section_id_course_id_key'), 'section_courses', ['section_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('election')
    # ### end Alembic commands ###
