"""add is_guide to courses

Revision ID: 38c8b9944d1c
Revises: 846435c7a23d
Create Date: 2026-03-30 16:18:40.130553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c8b9944d1c'
down_revision: Union[str, Sequence[str], None] = '846435c7a23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_guide', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_guide')
    # ### end Alembic commands ###
