"""add study plan models

Revision ID: 675261c2ffff
Revises: 900e8d42ddd8
Create Date: 2026-03-30 00:05:21.023018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675261c2ffff'
down_revision: Union[str, Sequence[str], None] = '900e8d42ddd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_courses',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'course_id')
    )
    op.create_table('section_study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_plan_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('enrollments', sa.Column('section_part', sa.String(length=1), nullable=False))
    op.add_column('section_courses', sa.Column('section_part', sa.String(length=1), nullable=True))
    op.drop_constraint(op.f('student_profiles_section_id_fkey'), 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'section_id')
    op.drop_column('student_profiles', 'section_part')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('section_part', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('student_profiles', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('student_profiles_section_id_fkey'), 'student_profiles', 'sections', ['section_id'], ['id'])
    op.drop_column('section_courses', 'section_part')
    op.drop_column('enrollments', 'section_part')
    op.drop_table('study_plan_courses')
    op.drop_table('section_study_plans')
    op.drop_table('professor_courses')
    op.drop_table('study_plans')
    # ### end Alembic commands ###
