"""init

Revision ID: ac50b688d399
Revises: f747cc41f4c7
Create Date: 2026-04-14 23:45:54.435737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac50b688d399'
down_revision: Union[str, Sequence[str], None] = 'f747cc41f4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('target_role', sa.String(length=50), nullable=True),
    sa.Column('target_section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['mail_id'], ['mails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_recipients',
    sa.Column('mail_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mail_id'], ['mails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('mail_id', 'user_id')
    )
    op.create_unique_constraint(None, 'enrollments', ['user_id', 'section_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='unique')
    op.drop_table('mail_recipients')
    op.drop_table('mail_attachments')
    op.drop_table('mails')
    # ### end Alembic commands ###
