"""init

Revision ID: fbad0c287c89
Revises: 
Create Date: 2026-04-10 01:52:09.576225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbad0c287c89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_course_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('lesson_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_course_id'], ['section_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ar_date', 'attendance_reports', ['date'], unique=False)
    op.create_index('ix_ar_professor', 'attendance_reports', ['professor_id'], unique=False)
    op.create_index('ix_ar_section_course', 'attendance_reports', ['section_course_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('presente', 'ausente', 'tardia', 'justificado', name='attendance_status'), nullable=False),
    sa.Column('justification', sa.String(length=500), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['attendance_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_arec_report', 'attendance_records', ['report_id'], unique=False)
    op.create_index('ix_arec_user', 'attendance_records', ['user_id'], unique=False)
    op.create_index('ix_arec_user_rep', 'attendance_records', ['user_id', 'report_id'], unique=False)
    op.drop_table('attendance')
    op.drop_constraint(op.f('administrative_profiles_user_id_fkey'), 'administrative_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'administrative_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('announcements', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('announcements_created_by_fkey'), 'announcements', type_='foreignkey')
    op.drop_constraint(op.f('announcements_target_section_id_fkey'), 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'announcements', 'sections', ['target_section_id'], ['id'])
    op.drop_constraint(op.f('applicant_documents_applicant_id_fkey'), 'applicant_documents', type_='foreignkey')
    op.drop_constraint(op.f('applicant_documents_reviewed_by_fkey'), 'applicant_documents', type_='foreignkey')
    op.create_foreign_key(None, 'applicant_documents', 'applicants', ['applicant_id'], ['id'])
    op.create_foreign_key(None, 'applicant_documents', 'users', ['reviewed_by'], ['id'])
    op.alter_column('applicant_interviews', 'interviewer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('applicant_interviews_interviewer_id_fkey'), 'applicant_interviews', type_='foreignkey')
    op.drop_constraint(op.f('applicant_interviews_applicant_id_fkey'), 'applicant_interviews', type_='foreignkey')
    op.create_foreign_key(None, 'applicant_interviews', 'applicants', ['applicant_id'], ['id'])
    op.create_foreign_key(None, 'applicant_interviews', 'users', ['interviewer_id'], ['id'])
    op.drop_constraint(op.f('applicant_tests_applicant_id_fkey'), 'applicant_tests', type_='foreignkey')
    op.drop_constraint(op.f('applicant_tests_administered_by_fkey'), 'applicant_tests', type_='foreignkey')
    op.create_foreign_key(None, 'applicant_tests', 'users', ['administered_by'], ['id'])
    op.create_foreign_key(None, 'applicant_tests', 'applicants', ['applicant_id'], ['id'])
    op.drop_constraint(op.f('applicants_reviewed_by_fkey'), 'applicants', type_='foreignkey')
    op.create_foreign_key(None, 'applicants', 'users', ['reviewed_by'], ['id'])
    op.drop_constraint(op.f('classroom_availability_slots_classroom_id_fkey'), 'classroom_availability_slots', type_='foreignkey')
    op.create_foreign_key(None, 'classroom_availability_slots', 'classrooms', ['classroom_id'], ['id'])
    op.alter_column('election', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('election', 'closed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('election_created_by_fkey'), 'election', type_='foreignkey')
    op.create_foreign_key(None, 'election', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('election_parties_election_id_fkey'), 'election_parties', type_='foreignkey')
    op.create_foreign_key(None, 'election_parties', 'election', ['election_id'], ['id'])
    op.drop_constraint(op.f('election_votes_revoked_by_fkey'), 'election_votes', type_='foreignkey')
    op.drop_constraint(op.f('election_votes_party_id_fkey'), 'election_votes', type_='foreignkey')
    op.drop_constraint(op.f('election_votes_election_id_fkey'), 'election_votes', type_='foreignkey')
    op.drop_constraint(op.f('election_votes_user_id_fkey'), 'election_votes', type_='foreignkey')
    op.create_foreign_key(None, 'election_votes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'election_votes', 'users', ['revoked_by'], ['id'])
    op.create_foreign_key(None, 'election_votes', 'election', ['election_id'], ['id'])
    op.create_foreign_key(None, 'election_votes', 'election_parties', ['party_id'], ['id'])
    op.create_unique_constraint(None, 'enrollments', ['user_id', 'section_id'])
    op.drop_constraint(op.f('enrollments_user_id_fkey'), 'enrollments', type_='foreignkey')
    op.drop_constraint(op.f('enrollments_section_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'sections', ['section_id'], ['id'])
    op.drop_constraint(op.f('evaluations_section_id_fkey'), 'evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'evaluations', 'sections', ['section_id'], ['id'])
    op.alter_column('events', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('events_target_section_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_created_by_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'sections', ['target_section_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['created_by'], ['id'])
    op.alter_column('grade_reports', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grade_reports', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grade_reports', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('grade_reports_section_id_fkey'), 'grade_reports', type_='foreignkey')
    op.drop_constraint(op.f('grade_reports_student_id_fkey'), 'grade_reports', type_='foreignkey')
    op.drop_constraint(op.f('grade_reports_period_id_fkey'), 'grade_reports', type_='foreignkey')
    op.create_foreign_key(None, 'grade_reports', 'users', ['student_id'], ['id'])
    op.create_foreign_key(None, 'grade_reports', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'grade_reports', 'academic_periods', ['period_id'], ['id'])
    op.drop_constraint(op.f('group_members_user_id_fkey'), 'group_members', type_='foreignkey')
    op.drop_constraint(op.f('group_members_group_id_fkey'), 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'group_members', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('groups_section_id_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'sections', ['section_id'], ['id'])
    op.drop_constraint(op.f('meeting_attendees_user_id_fkey'), 'meeting_attendees', type_='foreignkey')
    op.drop_constraint(op.f('meeting_attendees_meeting_id_fkey'), 'meeting_attendees', type_='foreignkey')
    op.create_foreign_key(None, 'meeting_attendees', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'meeting_attendees', 'meetings', ['meeting_id'], ['id'])
    op.alter_column('meetings', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('meetings_created_by_fkey'), 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('professor_availability_slots_professor_id_fkey'), 'professor_availability_slots', type_='foreignkey')
    op.create_foreign_key(None, 'professor_availability_slots', 'users', ['professor_id'], ['id'])
    op.drop_constraint(op.f('professor_courses_professor_id_fkey'), 'professor_courses', type_='foreignkey')
    op.drop_constraint(op.f('professor_courses_course_id_fkey'), 'professor_courses', type_='foreignkey')
    op.create_foreign_key(None, 'professor_courses', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'professor_courses', 'users', ['professor_id'], ['id'])
    op.drop_constraint(op.f('professor_profiles_user_id_fkey'), 'professor_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'professor_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_constraint(op.f('schedule_lessons_classroom_id_fkey'), 'schedule_lessons', type_='foreignkey')
    op.drop_constraint(op.f('schedule_lessons_section_course_id_fkey'), 'schedule_lessons', type_='foreignkey')
    op.drop_constraint(op.f('schedule_lessons_professor_id_fkey'), 'schedule_lessons', type_='foreignkey')
    op.drop_constraint(op.f('schedule_lessons_section_id_fkey'), 'schedule_lessons', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_lessons', 'section_courses', ['section_course_id'], ['id'])
    op.create_foreign_key(None, 'schedule_lessons', 'users', ['professor_id'], ['id'])
    op.create_foreign_key(None, 'schedule_lessons', 'classrooms', ['classroom_id'], ['id'])
    op.create_foreign_key(None, 'schedule_lessons', 'sections', ['section_id'], ['id'])
    op.drop_constraint(op.f('scholarships_student_id_fkey'), 'scholarships', type_='foreignkey')
    op.drop_constraint(op.f('scholarships_granted_by_fkey'), 'scholarships', type_='foreignkey')
    op.create_foreign_key(None, 'scholarships', 'users', ['granted_by'], ['id'])
    op.create_foreign_key(None, 'scholarships', 'student_profiles', ['student_id'], ['user_id'])
    op.drop_constraint(op.f('section_courses_section_id_fkey'), 'section_courses', type_='foreignkey')
    op.drop_constraint(op.f('section_courses_course_id_fkey'), 'section_courses', type_='foreignkey')
    op.drop_constraint(op.f('section_courses_professor_id_fkey'), 'section_courses', type_='foreignkey')
    op.create_foreign_key(None, 'section_courses', 'users', ['professor_id'], ['id'])
    op.create_foreign_key(None, 'section_courses', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'section_courses', 'courses', ['course_id'], ['id'])
    op.drop_constraint(op.f('section_specialties_section_id_fkey'), 'section_specialties', type_='foreignkey')
    op.drop_constraint(op.f('section_specialties_specialty_id_fkey'), 'section_specialties', type_='foreignkey')
    op.create_foreign_key(None, 'section_specialties', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'section_specialties', 'specialties', ['specialty_id'], ['id'])
    op.drop_constraint(op.f('section_study_plans_study_plan_id_fkey'), 'section_study_plans', type_='foreignkey')
    op.drop_constraint(op.f('section_study_plans_section_id_fkey'), 'section_study_plans', type_='foreignkey')
    op.create_foreign_key(None, 'section_study_plans', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'section_study_plans', 'study_plans', ['study_plan_id'], ['id'])
    op.drop_constraint(op.f('sections_guide_professor_id_fkey'), 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'users', ['guide_professor_id'], ['id'])
    op.drop_constraint(op.f('student_profiles_converted_from_applicant_id_fkey'), 'student_profiles', type_='foreignkey')
    op.drop_constraint(op.f('student_profiles_user_id_fkey'), 'student_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'student_profiles', 'applicants', ['converted_from_applicant_id'], ['id'])
    op.create_foreign_key(None, 'student_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('study_plan_courses_study_plan_id_fkey'), 'study_plan_courses', type_='foreignkey')
    op.drop_constraint(op.f('study_plan_courses_course_id_fkey'), 'study_plan_courses', type_='foreignkey')
    op.create_foreign_key(None, 'study_plan_courses', 'study_plans', ['study_plan_id'], ['id'])
    op.create_foreign_key(None, 'study_plan_courses', 'courses', ['course_id'], ['id'])
    op.drop_constraint(op.f('submissions_evaluation_id_fkey'), 'submissions', type_='foreignkey')
    op.drop_constraint(op.f('submissions_graded_by_fkey'), 'submissions', type_='foreignkey')
    op.drop_constraint(op.f('submissions_user_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'evaluations', ['evaluation_id'], ['id'])
    op.create_foreign_key(None, 'submissions', 'users', ['graded_by'], ['id'])
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_user_id_fkey'), 'submissions', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('submissions_graded_by_fkey'), 'submissions', 'users', ['graded_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('submissions_evaluation_id_fkey'), 'submissions', 'evaluations', ['evaluation_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'study_plan_courses', type_='foreignkey')
    op.drop_constraint(None, 'study_plan_courses', type_='foreignkey')
    op.create_foreign_key(op.f('study_plan_courses_course_id_fkey'), 'study_plan_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('study_plan_courses_study_plan_id_fkey'), 'study_plan_courses', 'study_plans', ['study_plan_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('student_profiles_user_id_fkey'), 'student_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_profiles_converted_from_applicant_id_fkey'), 'student_profiles', 'applicants', ['converted_from_applicant_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key(op.f('sections_guide_professor_id_fkey'), 'sections', 'users', ['guide_professor_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'section_study_plans', type_='foreignkey')
    op.drop_constraint(None, 'section_study_plans', type_='foreignkey')
    op.create_foreign_key(op.f('section_study_plans_section_id_fkey'), 'section_study_plans', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('section_study_plans_study_plan_id_fkey'), 'section_study_plans', 'study_plans', ['study_plan_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'section_specialties', type_='foreignkey')
    op.drop_constraint(None, 'section_specialties', type_='foreignkey')
    op.create_foreign_key(op.f('section_specialties_specialty_id_fkey'), 'section_specialties', 'specialties', ['specialty_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('section_specialties_section_id_fkey'), 'section_specialties', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'section_courses', type_='foreignkey')
    op.drop_constraint(None, 'section_courses', type_='foreignkey')
    op.drop_constraint(None, 'section_courses', type_='foreignkey')
    op.create_foreign_key(op.f('section_courses_professor_id_fkey'), 'section_courses', 'users', ['professor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('section_courses_course_id_fkey'), 'section_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('section_courses_section_id_fkey'), 'section_courses', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'scholarships', type_='foreignkey')
    op.drop_constraint(None, 'scholarships', type_='foreignkey')
    op.create_foreign_key(op.f('scholarships_granted_by_fkey'), 'scholarships', 'users', ['granted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('scholarships_student_id_fkey'), 'scholarships', 'student_profiles', ['student_id'], ['user_id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'schedule_lessons', type_='foreignkey')
    op.drop_constraint(None, 'schedule_lessons', type_='foreignkey')
    op.drop_constraint(None, 'schedule_lessons', type_='foreignkey')
    op.drop_constraint(None, 'schedule_lessons', type_='foreignkey')
    op.create_foreign_key(op.f('schedule_lessons_section_id_fkey'), 'schedule_lessons', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('schedule_lessons_professor_id_fkey'), 'schedule_lessons', 'users', ['professor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('schedule_lessons_section_course_id_fkey'), 'schedule_lessons', 'section_courses', ['section_course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('schedule_lessons_classroom_id_fkey'), 'schedule_lessons', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'professor_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('professor_profiles_user_id_fkey'), 'professor_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'professor_courses', type_='foreignkey')
    op.drop_constraint(None, 'professor_courses', type_='foreignkey')
    op.create_foreign_key(op.f('professor_courses_course_id_fkey'), 'professor_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('professor_courses_professor_id_fkey'), 'professor_courses', 'users', ['professor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'professor_availability_slots', type_='foreignkey')
    op.create_foreign_key(op.f('professor_availability_slots_professor_id_fkey'), 'professor_availability_slots', 'users', ['professor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key(op.f('meetings_created_by_fkey'), 'meetings', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('meetings', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'meeting_attendees', type_='foreignkey')
    op.drop_constraint(None, 'meeting_attendees', type_='foreignkey')
    op.create_foreign_key(op.f('meeting_attendees_meeting_id_fkey'), 'meeting_attendees', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('meeting_attendees_user_id_fkey'), 'meeting_attendees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_section_id_fkey'), 'groups', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(op.f('group_members_group_id_fkey'), 'group_members', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('group_members_user_id_fkey'), 'group_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'grade_reports', type_='foreignkey')
    op.drop_constraint(None, 'grade_reports', type_='foreignkey')
    op.drop_constraint(None, 'grade_reports', type_='foreignkey')
    op.create_foreign_key(op.f('grade_reports_period_id_fkey'), 'grade_reports', 'academic_periods', ['period_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('grade_reports_student_id_fkey'), 'grade_reports', 'users', ['student_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('grade_reports_section_id_fkey'), 'grade_reports', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
    op.alter_column('grade_reports', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grade_reports', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grade_reports', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_created_by_fkey'), 'events', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('events_target_section_id_fkey'), 'events', 'sections', ['target_section_id'], ['id'], ondelete='SET NULL')
    op.alter_column('events', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('evaluations_section_id_fkey'), 'evaluations', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_section_id_fkey'), 'enrollments', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('enrollments_user_id_fkey'), 'enrollments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'enrollments', type_='unique')
    op.drop_constraint(None, 'election_votes', type_='foreignkey')
    op.drop_constraint(None, 'election_votes', type_='foreignkey')
    op.drop_constraint(None, 'election_votes', type_='foreignkey')
    op.drop_constraint(None, 'election_votes', type_='foreignkey')
    op.create_foreign_key(op.f('election_votes_user_id_fkey'), 'election_votes', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('election_votes_election_id_fkey'), 'election_votes', 'election', ['election_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('election_votes_party_id_fkey'), 'election_votes', 'election_parties', ['party_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('election_votes_revoked_by_fkey'), 'election_votes', 'users', ['revoked_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'election_parties', type_='foreignkey')
    op.create_foreign_key(op.f('election_parties_election_id_fkey'), 'election_parties', 'election', ['election_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.create_foreign_key(op.f('election_created_by_fkey'), 'election', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('election', 'closed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('election', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'classroom_availability_slots', type_='foreignkey')
    op.create_foreign_key(op.f('classroom_availability_slots_classroom_id_fkey'), 'classroom_availability_slots', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'applicants', type_='foreignkey')
    op.create_foreign_key(op.f('applicants_reviewed_by_fkey'), 'applicants', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'applicant_tests', type_='foreignkey')
    op.drop_constraint(None, 'applicant_tests', type_='foreignkey')
    op.create_foreign_key(op.f('applicant_tests_administered_by_fkey'), 'applicant_tests', 'users', ['administered_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('applicant_tests_applicant_id_fkey'), 'applicant_tests', 'applicants', ['applicant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'applicant_interviews', type_='foreignkey')
    op.drop_constraint(None, 'applicant_interviews', type_='foreignkey')
    op.create_foreign_key(op.f('applicant_interviews_applicant_id_fkey'), 'applicant_interviews', 'applicants', ['applicant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('applicant_interviews_interviewer_id_fkey'), 'applicant_interviews', 'users', ['interviewer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('applicant_interviews', 'interviewer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'applicant_documents', type_='foreignkey')
    op.drop_constraint(None, 'applicant_documents', type_='foreignkey')
    op.create_foreign_key(op.f('applicant_documents_reviewed_by_fkey'), 'applicant_documents', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('applicant_documents_applicant_id_fkey'), 'applicant_documents', 'applicants', ['applicant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key(op.f('announcements_target_section_id_fkey'), 'announcements', 'sections', ['target_section_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('announcements_created_by_fkey'), 'announcements', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('announcements', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'administrative_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('administrative_profiles_user_id_fkey'), 'administrative_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('present', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('late', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('justification', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('recorded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('attendance_recorded_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('attendance_section_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attendance_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey'))
    )
    op.drop_index('ix_arec_user_rep', table_name='attendance_records')
    op.drop_index('ix_arec_user', table_name='attendance_records')
    op.drop_index('ix_arec_report', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('ix_ar_section_course', table_name='attendance_reports')
    op.drop_index('ix_ar_professor', table_name='attendance_reports')
    op.drop_index('ix_ar_date', table_name='attendance_reports')
    op.drop_table('attendance_reports')
    # ### end Alembic commands ###
